
[colors.primary]
background = '#12140d'
foreground = '#e3e3d7'
 
[colors.cursor]
text = '#e3e3d7'
cursor = '#c6c8b8' 
 
[colors.vi_mode_cursor]
text = '#12140d'
cursor = '#bacf82' 
 
[colors.search.matches]
foreground = '#46483c' 
background = '#a1d0c7' 
 
[colors.search.focused_match]
foreground = '#46483c' 
background = '#bacf82' 
 
[colors.footer_bar]
foreground = '#46483c' 
background = '#e3e3d7' 
 
[colors.hints.start]
foreground = '#46483c' 
background = '#c3caaa' 
 
[colors.hints.end]
foreground = '#46483c' 
background = '#c3caaa' 
 
[colors.selection]
text = '#12140d'
background = '#bacf82'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#bacf82' 
yellow = '#536524' 
blue = '#bacf82' 
magenta = '#a1d0c7' 
cyan = '#c3caaa' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 
